# Generated by Django 4.1.5 on 2023-01-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hasil_no",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hasil_no", models.CharField(max_length=200, verbose_name="Hasil No")),
            ],
        ),
        migrations.CreateModel(
            name="indikator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indikator",
                    models.CharField(max_length=200, verbose_name="Nama Indikator"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="rute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indikator1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Indikator_1",
                        to="ekobistren.indikator",
                    ),
                ),
                (
                    "indikator2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Indikator_2",
                        to="ekobistren.indikator",
                    ),
                ),
            ],
        ),
    ]
