# Generated by Django 4.1.5 on 2023-01-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekobistren", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="pondok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_pondok",
                    models.CharField(max_length=200, verbose_name="Nama Pondok"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hasil_no",
            name="keterangan",
            field=models.TextField(default=1, verbose_name="Keterangan"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="indikator",
            name="keterangan",
            field=models.TextField(default=1, verbose_name="Keterangan"),
            preserve_default=False,
        ),
    ]
